[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv venv",
  "chmod +x venv/bin/activate",  # Ensuring the virtual environment activation script is executable
  ". venv/bin/activate && pip install --upgrade pip",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "chmod -R 755 .",  # Grant read/write/execute permissions to all files in the project
  ". venv/bin/activate && python manage.py makemigrations",
  ". venv/bin/activate && python manage.py migrate",
  ". venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = "chmod -R 755 . && . venv/bin/activate && gunicorn todo_site.wsgi:application --bind 0.0.0.0:${PORT:-3000}"  # Updated to use gunicorn

[variables]
PORT = "3000"
PYTHONUNBUFFERED = "1"
DEBUG = "False"
ALLOWED_HOSTS = "z88wo4k88484w8w0kg4sck8s.69.62.73.79.sslip.io,localhost,127.0.0.1"
