[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv venv",
  ". venv/bin/activate && pip install --upgrade pip",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". venv/bin/activate && python manage.py makemigrations",
  ". venv/bin/activate && python manage.py migrate"
]

[start]
cmd = ". venv/bin/activate && python manage.py runserver 0.0.0.0:${PORT}"

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"
DEBUG = "False"
ALLOWED_HOSTS = "*"
