[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv venv",
  ". venv/bin/activate && pip install --upgrade pip",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". venv/bin/activate && python manage.py makemigrations",
  ". venv/bin/activate && python manage.py migrate",
  ". venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = ". venv/bin/activate && python manage.py runserver 0.0.0.0:${PORT:-8000}"

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"
DEBUG = "False"
ALLOWED_HOSTS = "z88wo4k88484w8w0kg4sck8s.69.62.73.79.sslip.io,localhost,127.0.0.1"
